// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVDKZTwqzooAeOeajEPJfUby1k3GtBlvU',
    appId: '1:512178117744:web:f02c691ef1d25586f2a8b5',
    messagingSenderId: '512178117744',
    projectId: 'ditik-apps-mynotes',
    authDomain: 'ditik-apps-mynotes.firebaseapp.com',
    storageBucket: 'ditik-apps-mynotes.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5Z0D4pQKhdx2pu-9B5DuHjmKaPCPojMI',
    appId: '1:512178117744:android:700ccd3d676eef83f2a8b5',
    messagingSenderId: '512178117744',
    projectId: 'ditik-apps-mynotes',
    storageBucket: 'ditik-apps-mynotes.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC865W_elVXSRvlKYzXr2keHmL8_3dzwZs',
    appId: '1:512178117744:ios:b07b0202725420a2f2a8b5',
    messagingSenderId: '512178117744',
    projectId: 'ditik-apps-mynotes',
    storageBucket: 'ditik-apps-mynotes.appspot.com',
    iosClientId:
        '512178117744-lv3vggkbe6kde901n6q9j7bedp79j510.apps.googleusercontent.com',
    iosBundleId: 'com.example.myfirstapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC865W_elVXSRvlKYzXr2keHmL8_3dzwZs',
    appId: '1:512178117744:ios:35b9230f1f0ff1f8f2a8b5',
    messagingSenderId: '512178117744',
    projectId: 'ditik-apps-mynotes',
    storageBucket: 'ditik-apps-mynotes.appspot.com',
    iosClientId:
        '512178117744-2ihc0meq049ih0lp60tb4c6lftkeuo8g.apps.googleusercontent.com',
    iosBundleId: 'com.example.myfirstapp.RunnerTests',
  );
}
